### ISSUE TITLE
[Recruiter] View List of Candidates Per Job

### ISSUE THREAD

**Issue by devstein** [shared-recruiting-co/shared-recruiting-co#165]
**Is your feature request related to a problem? Please describe.**
As a recruiter, I want to view candidates I've reached out for a specific role.

**Describe the solution you'd like**
A dedicated page per job in the recruiting account pages

**Additional context**
There will be follow up issues for metrics and filters for candidates in different stages

**Comment by Noothan-am** [comment]
hi,
i want to contribute to this but i am facing problem in setting this project locally how to overcome this problem ?

![image](https://user-images.githubusercontent.com/100135382/225976743-31de1c67-736a-4eee-8451-d9e5ea40ef9e.png)

**Comment by devstein** [comment]
Hi @Noothan-am, happy to hear you want to contribute! I just [updated the README](https://github.com/shared-recruiting-co/shared-recruiting-co/commit/9f3c6ec4d756f554db30d78fae0d4b490388e1b8) with instructions on how to setup your local environment variables. Once you setup your `.env.local` file, this error will go away.

I must warn you that SRC is under active development and doesn't have the structure in place to make it easy to contribute to. I'm working hard to change this. In the meantime, please let me know if you run into more issues or have questions. I'm here to help!

**Comment by devstein** [comment]
Closed by #185
