### ISSUE TITLE
[Candidate] Allow Candidates to Remove Misattributed Jobs

### ISSUE THREAD

**Issue by msteinbrick** [shared-recruiting-co/shared-recruiting-co#177]
**Is your feature request related to a problem? Please describe.**
If a candidate currently sees an opportunity on their  [job board](https://sharedrecruiting.co/account/jobs) that is misattributed (ie. the email was mislabeled and is not a job opportunity), they have no way to remove it.

**Describe the solution you'd like**
A candidate should be able to click a "Not an opportunity" button on the job board table to: (1) remove the opportunity from the job board and (2) remove the label from the email in the gmail account

**Comment by msteinbrick** [comment]
@devstein - this seems about the simplest task to get started with UI changes and understanding the Go cloud functions. Let me know you think. If this isn't necessary I'll look into https://github.com/shared-recruiting-co/shared-recruiting-co/issues/175

**Comment by devstein** [comment]
For naming, I would just call the button `Remove` or `Delete`

**Comment by devstein** [comment]
Also good opportunity to add documentation to making database schema changes
