### ISSUE TITLE
[Web] Pagination Refactor

### ISSUE THREAD

**Issue by devstein** [shared-recruiting-co/shared-recruiting-co#202]
**Is your feature request related to a problem? Please describe.**
We now have >3 tables with the same styling and pagination patterns. We already have [a pagination library](https://github.com/shared-recruiting-co/shared-recruiting-co/blob/main/web/src/lib/pagination.ts ), but there is more we can add to it. Namely,

1. The Pagination type used in all the load functions
2. The logic to get the pagination params in the load functions
3. The TableFooter component is identical in each table and not data dependent. The component should hide itself if there are not multiple pages.

**Describe the solution you'd like**
```ts
type Pagination = {
	page: number;
	perPage: number;
        start: number;
        stop: number;
	numPages: number;
	numResults: number;
	hasNext: boolean;
	hasPrev: boolean;
};

export const DEFAULT_PAGE_SIZE = 10;
const getPagePagination = (url: URL, pageSize = DEFAULT_PAGE_SIZE ): Pagination => {
// ...
};
```

```svelte
<TableFooter {pagination} />
```

**Additional context**
Two PRs
1. Create the shared library
2. Refactor to use shared types/func/component in every related page

**Comment by Yasir761** [comment]
I want to work on this issue, can you please assign it to me?

**Comment by devstein** [comment]
Hi @Yasir761 any updates on this?

**Comment by PawanAK** [comment]
i want to solve this issue , can u assign this to me ?

**Comment by devstein** [comment]
Hi @PawanAK feel free to tackle this issue. I'll assign it to you once you create a PR

**Comment by msteinbrick** [comment]
Hey sorry @PawanAK - was taking a look at this earlier, just opened a PR here: https://github.com/shared-recruiting-co/shared-recruiting-co/pull/251

**Comment by devstein** [comment]
Thanks @msteinbrick!
